### PR TITLE
added folder for ips

### PR DESCRIPTION
**Pull request by Brenn10**
Added a place to place our ips' source codes for future maintenance.

### CODE REVIEW

**Comment by drichmond** [comment]
This already exists, unfortunately. See pynqcopter/ip

**Comment by Brenn10** [comment]
I see

**Comment by drichmond** [comment]
Also, you should try to avoid committing the metadata files that Vivado HLS creates. Best practice is to create a makefile, and the .cpp/.h files. 

I can help with this

**Comment by Brenn10** [comment]
I was just uploading the project, but i'll clean it up before I submit a pull request

**Pull request closed without merging**
